basePath: /
definitions:
  main.album:
    description: Esta API retorna e adiciona álbuns musicais.
    properties:
      artist:
        type: string
      id:
        type: string
      price:
        type: number
      title:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: Esta API retorna e adiciona álbuns musicais.
  title: API de Álbuns
  version: "1.0"
paths:
  /albums:
    get:
      consumes:
      - application/json
      description: get all albums
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/main.album'
            type: array
      summary: List all albums
      tags:
      - albums
    post:
      consumes:
      - application/json
      description: add a new album
      parameters:
      - description: Album to add
        in: body
        name: album
        required: true
        schema:
          $ref: '#/definitions/main.album'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/main.album'
      summary: Add a new album
      tags:
      - albums
  /albums/{id}:
    get:
      consumes:
      - application/json
      description: get album by ID
      parameters:
      - description: Album ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.album'
      summary: Get an album by ID
      tags:
      - albums
swagger: "2.0"
